
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global
[<assembly: Android.Runtime.ResourceDesignerAttribute("Dummy6.Resource", IsApplication=true)>]
    do ()

namespace XamarinStore
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnExceptiond2e21335c73f43be8f4e0db21e35cbdc of obj
    exception ReturnNoneExceptiond2e21335c73f43be8f4e0db21e35cbdc
    [<AutoOpen>]
    module FuncConvertFinalOverloadd2e21335c73f43be8f4e0db21e35cbdc =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                ()


    
    and
        
        (* partial *)Resource_Animation () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f040000
            static member add_to_basket_in = 2130968576
            
            // aapt resource value: 0x7f040001
            static member basket_in = 2130968577
            
            // aapt resource value: 0x7f040002
            static member enter = 2130968578
            
            // aapt resource value: 0x7f040003
            static member exit = 2130968579
            
            // aapt resource value: 0x7f040004
            static member product_detail_in = 2130968580
            
            // aapt resource value: 0x7f040005
            static member product_detail_out = 2130968581
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Color () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f050008
            static member ab_background = 2131034120
            
            // aapt resource value: 0x7f050009
            static member ab_bottom_shadow_1 = 2131034121
            
            // aapt resource value: 0x7f05000a
            static member ab_bottom_shadow_2 = 2131034122
            
            // aapt resource value: 0x7f050007
            static member action_bar_title_color = 2131034119
            
            // aapt resource value: 0x7f05000b
            static member btn_bg_color = 2131034123
            
            // aapt resource value: 0x7f05000c
            static member btn_bg_shadow_color = 2131034124
            
            // aapt resource value: 0x7f050006
            static member main_background = 2131034118
            
            // aapt resource value: 0x7f050001
            static member xam_blue = 2131034113
            
            // aapt resource value: 0x7f050002
            static member xam_dark_blue = 2131034114
            
            // aapt resource value: 0x7f050004
            static member xam_gray = 2131034116
            
            // aapt resource value: 0x7f050003
            static member xam_green = 2131034115
            
            // aapt resource value: 0x7f050005
            static member xam_light_gray = 2131034117
            
            // aapt resource value: 0x7f050000
            static member xam_purple = 2131034112
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Dimension () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f070000
            static member btn_corner_radius = 2131165184
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Drawable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            static member ab_background = 2130837504
            
            // aapt resource value: 0x7f020001
            static member blue_shirt = 2130837505
            
            // aapt resource value: 0x7f020002
            static member btn_bg = 2130837506
            
            // aapt resource value: 0x7f020003
            static member btn_bg_inactive = 2130837507
            
            // aapt resource value: 0x7f020004
            static member btn_bg_normal = 2130837508
            
            // aapt resource value: 0x7f020005
            static member btn_bg_pressed = 2130837509
            
            // aapt resource value: 0x7f020006
            static member cart = 2130837510
            
            // aapt resource value: 0x7f020007
            static member complete = 2130837511
            
            // aapt resource value: 0x7f020008
            static member configure = 2130837512
            
            // aapt resource value: 0x7f020009
            static member discrete_shadow = 2130837513
            
            // aapt resource value: 0x7f02000a
            static member dummy_avatar = 2130837514
            
            // aapt resource value: 0x7f02000b
            static member empty_basket = 2130837515
            
            // aapt resource value: 0x7f02000c
            static member gallery_next = 2130837516
            
            // aapt resource value: 0x7f02000d
            static member gallery_prev = 2130837517
            
            // aapt resource value: 0x7f02000e
            static member ic_action_basket = 2130837518
            
            // aapt resource value: 0x7f02000f
            static member ic_action_logo = 2130837519
            
            // aapt resource value: 0x7f020010
            static member Icon = 2130837520
            
            // aapt resource value: 0x7f020011
            static member monkey = 2130837521
            
            // aapt resource value: 0x7f020012
            static member processing = 2130837522
            
            // aapt resource value: 0x7f020013
            static member ProductImage = 2130837523
            
            // aapt resource value: 0x7f020014
            static member purple_shirt = 2130837524
            
            // aapt resource value: 0x7f020015
            static member shirt_image = 2130837525
            
            // aapt resource value: 0x7f020016
            static member user_default_avatar = 2130837526
            
            // aapt resource value: 0x7f020017
            static member wrench = 2130837527
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Id () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f0a0024
            static member City = 2131361828
            
            // aapt resource value: 0x7f0a0026
            static member Country = 2131361830
            
            // aapt resource value: 0x7f0a001f
            static member FirstName = 2131361823
            
            // aapt resource value: 0x7f0a0020
            static member LastName = 2131361824
            
            // aapt resource value: 0x7f0a0021
            static member Phone = 2131361825
            
            // aapt resource value: 0x7f0a0028
            static member PlaceOrder = 2131361832
            
            // aapt resource value: 0x7f0a0025
            static member PostalCode = 2131361829
            
            // aapt resource value: 0x7f0a0027
            static member State = 2131361831
            
            // aapt resource value: 0x7f0a0022
            static member StreetAddress1 = 2131361826
            
            // aapt resource value: 0x7f0a0023
            static member StreetAddress2 = 2131361827
            
            // aapt resource value: 0x7f0a000b
            static member SwipeAfter = 2131361803
            
            // aapt resource value: 0x7f0a0002
            static member SwipeContainer = 2131361794
            
            // aapt resource value: 0x7f0a0003
            static member SwipeContent = 2131361795
            
            // aapt resource value: 0x7f0a001c
            static member addToBasket = 2131361820
            
            // aapt resource value: 0x7f0a0010
            static member bragButton = 2131361808
            
            // aapt resource value: 0x7f0a000e
            static member button1 = 2131361806
            
            // aapt resource value: 0x7f0a0029
            static member cart_menu_item = 2131361833
            
            // aapt resource value: 0x7f0a0000
            static member checkoutBtn = 2131361792
            
            // aapt resource value: 0x7f0a0016
            static member codeTextView = 2131361814
            
            // aapt resource value: 0x7f0a0015
            static member contentArea = 2131361813
            
            // aapt resource value: 0x7f0a0018
            static member descriptionLayout = 2131361816
            
            // aapt resource value: 0x7f0a0011
            static member email = 2131361809
            
            // aapt resource value: 0x7f0a0014
            static member error = 2131361812
            
            // aapt resource value: 0x7f0a0017
            static member explanationTextView = 2131361815
            
            // aapt resource value: 0x7f0a0001
            static member imageView1 = 2131361793
            
            // aapt resource value: 0x7f0a000f
            static member linearLayout1 = 2131361807
            
            // aapt resource value: 0x7f0a0005
            static member linearLayout2 = 2131361797
            
            // aapt resource value: 0x7f0a0006
            static member linearLayout3 = 2131361798
            
            // aapt resource value: 0x7f0a0012
            static member password = 2131361810
            
            // aapt resource value: 0x7f0a000a
            static member productColor = 2131361802
            
            // aapt resource value: 0x7f0a0019
            static member productDescription = 2131361817
            
            // aapt resource value: 0x7f0a0004
            static member productImage = 2131361796
            
            // aapt resource value: 0x7f0a001d
            static member productImageSpinner = 2131361821
            
            // aapt resource value: 0x7f0a0008
            static member productPrice = 2131361800
            
            // aapt resource value: 0x7f0a0009
            static member productSize = 2131361801
            
            // aapt resource value: 0x7f0a0007
            static member productTitle = 2131361799
            
            // aapt resource value: 0x7f0a001e
            static member scrollView1 = 2131361822
            
            // aapt resource value: 0x7f0a0013
            static member signInBtn = 2131361811
            
            // aapt resource value: 0x7f0a001a
            static member tableLayout1 = 2131361818
            
            // aapt resource value: 0x7f0a000c
            static member textView1 = 2131361804
            
            // aapt resource value: 0x7f0a001b
            static member textView4 = 2131361819
            
            // aapt resource value: 0x7f0a000d
            static member view1 = 2131361805
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Layout () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f030000
            static member Basket = 2130903040
            
            // aapt resource value: 0x7f030001
            static member BasketItem = 2130903041
            
            // aapt resource value: 0x7f030002
            static member BragScreen = 2130903042
            
            // aapt resource value: 0x7f030003
            static member LoginScreen = 2130903043
            
            // aapt resource value: 0x7f030004
            static member Main = 2130903044
            
            // aapt resource value: 0x7f030005
            static member PrefillXamarinAccountInstructions = 2130903045
            
            // aapt resource value: 0x7f030006
            static member ProductCell = 2130903046
            
            // aapt resource value: 0x7f030007
            static member ProductDetail = 2130903047
            
            // aapt resource value: 0x7f030008
            static member ProductListItem = 2130903048
            
            // aapt resource value: 0x7f030009
            static member ShippingDetails = 2130903049
            
            // aapt resource value: 0x7f03000a
            static member XamarinListLayout = 2130903050
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Menu () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f090000
            static member menu = 2131296256
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f060001
            static member app_name = 2131099649
            
            // aapt resource value: 0x7f060002
            static member brag_on = 2131099650
            
            // aapt resource value: 0x7f060003
            static member brag_to_friends = 2131099651
            
            // aapt resource value: 0x7f060000
            static member hello = 2131099648
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Style () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f080001
            static member XamActionBarStyle = 2131230721
            
            // aapt resource value: 0x7f080000
            static member XamActionBarTheme = 2131230720
            
            // aapt resource value: 0x7f080002
            static member XamActionBarTitleStyle = 2131230722
            
            // aapt resource value: 0x7f080005
            static member XamButton = 2131230725
            
            // aapt resource value: 0x7f080004
            static member XamSubtitleText = 2131230724
            
            // aapt resource value: 0x7f080003
            static member XamTitleText = 2131230723
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

